package main

const (
	dcIterFile = "dc_iter.txt"
	dcKeysFile = "dc_keys.txt"
	dcAddrFile = "dc_addr.txt"
)

type dcRequest struct {
	Iteration uint64    `json:"iteration"`
	Generated byte      `json:"generated"`
	ReqToken  *reqToken `json:"req_token"`
}

type reqToken struct {
	Addr string `json:"addr"`
	Salt []byte `json:"salt"`
	Mac  []byte `json:"mac"`
}
